Add search, depends sub-commands to pkg

diff --git a/ports/pkg/pkg b/ports/pkg/pkg
--- a/ports/pkg/pkg
+++ b/ports/pkg/pkg
@@ -189,6 +189,59 @@ pkg_list() {
   cd - > /dev/null
 }
 
+pkg_depends() {
+  q="$1"
+
+  if [ -z "$q" ]; then
+    Pkgfile="./Pkgfile"
+  else
+    Pkgfile="$PKG_PORTSDIR/$q/Pkgfile"
+  fi
+
+  [ -f "$Pkgfile" ] || die "Pkgfile not found"
+  . "$Pkgfile" || die "syntax error in Pkgfile"
+
+  if [ ! -t 1 ]; then
+    printf "%s\n" "$depends"
+  else
+    for dep in $depends; do
+      is_installed=" "
+      if pkg_list "$dep" > /dev/null; then
+        is_installed="X"
+      fi
+
+      printf "[%s] %s\n" "$is_installed" "$dep"
+    done
+  fi
+}
+
+pkg_search() {
+  q="$1"
+  matches="$(mktemp -t pkg-search-XXXXXX)"
+  for port in "$PKG_PORTSDIR"/*; do
+    [ -d "$port" ] || continue
+    grep -c -i -n -H -E "(# Description.*|URL|name=).*$q.*" "$port/Pkgfile"
+  done |
+    sort -n -r -t':' -k 2 |
+    grep -v '^.*\:0$' |
+    head \
+      > "$matches"
+
+  IFS=
+  while read -r line; do
+    port="$(echo "$line" | cut -f 1 -d':')"
+
+    name="$(grep -E '^name=' "$port" | cut -f 2 -d'=')"
+    vers="$(grep -E '^version=' "$port" | cut -f 2 -d'=')"
+    desc="$(grep -i -E '# Description' "$port" | cut -f 2 -d':')"
+    if [ -t 1 ]; then
+      printf "%10s %10s %s\n" "$name" "$vers" "$desc"
+    else
+      printf "%s %s %s\n" "$name" "$vers" "$desc"
+    fi
+  done < "$matches"
+}
+
 pkg_clean() {
   rm -f ./*#*
   rm -rf ./"build"
@@ -260,17 +313,22 @@ args() {
       pkg_checksum .checksum
       ;;
 
+    dep*) pkg_depends "$2" ;;
+
     d*) pkg_delete "$2" ;;
     l*) pkg_list "$2" ;;
+    s*) pkg_search "$2" ;;
     -v) printf '%s\n' "pkg 0.1.0" ;;
 
     *)
       log 'pkg [a]dd pkg.tar.gz' \
         'pkg [b]uild' \
-        'pkg [cl]ean' \
         'pkg [c]hecksum' \
+        'pkg [cl]ean' \
         'pkg [d]el pkg' \
-        'pkg [l]ist [pkg]'
+        'pkg [dep]ends pkg' \
+        'pkg [l]ist [pkg]' \
+        'pkg [s]earch [pattern]'
       ;;
   esac
 }
