Add basic support for network-config (tested with Proxmox VE 6.1)

diff --git a/rootfs/sbin/cloudinit b/rootfs/sbin/cloudinit
--- a/rootfs/sbin/cloudinit
+++ b/rootfs/sbin/cloudinit
@@ -43,13 +43,67 @@ parse_yaml() {
   awk "${YAML_AWK_PARSER}" "${1}"
 }
 
+netmask2cidr() {
+  bits=0
+  for octet in $(echo "$1" | sed 's/\./ /g'); do 
+    binbits=$(echo "obase=2; ibase=10; ${octet}"| bc | sed 's/0//g') 
+    bits=$((bits + ${#binbits}))
+  done
+  printf "%d" "${bits}"
+}
+
+networkconfig() {
+  cfg="$(mktemp -t network-config-XXXXXX)"
+
+  parse_yaml "$1" > "$cfg"
+
+  dev="$(grep "0_name" "$cfg" | cut -f 2 -d '=' | sed -e 's/^"//' -e 's/"$//')"
+  type="$(grep "0_0_type" "$cfg" | cut -f 2 -d '=' | sed -e 's/^"//' -e 's/"$//')"
+  addr="$(grep "0_0_address" "$cfg" | cut -f 2 -d '=' | sed -e 's/^"//' -e 's/"$//' | sed -e "s/^'//" -e "s/'$//")"
+  mask="$(netmask2cidr "$(grep "0_0_netmask" "$cfg" | cut -f 2 -d '=' | sed -e 's/^"//' -e 's/"$//' | sed -e "s/^'//" -e "s/'$//")")"
+  gw="$(grep "0_0_gateway" "$cfg" | cut -f 2 -d '=' | sed -e 's/^"//' -e 's/"$//' | sed -e "s/^'//" -e "s/'$//")"
+
+  ns1="$(grep "__1_0" "$cfg" | cut -f 2 -d '=' | sed -e 's/^"//' -e 's/"$//' | sed -e "s/^'//" -e "s/'$//")"
+  domain="$(grep "__1_1" "$cfg" | cut -f 2 -d '=' | sed -e 's/^"//' -e 's/"$//' | sed -e "s/^'//" -e "s/'$//")"
+
+  rm -rf "$cfg"
+
+  if [ "$type" = "dhcp" ]; then
+    cat > /etc/default/net <<EOF
+# Auto Generated by network-config
+TYPE="dhcp"
+DEV="$DEVICE"
+EOF
+  else
+    cat > /etc/default/net <<EOF
+# Auto Generated by network-config
+TYPE="static"
+DEV="$dev"
+ADDR="$addr"
+MASK="$mask"
+GW="$gw"
+EOF
+  fi
+
+  if [ -n "$ns1" ]; then
+    cat > /etc/resolv.conf <<EOF
+# Auto Generated by network-config
+nameserver $ns1
+EOF
+    if [ -n "$domain" ]; then
+      echo "search $domain" >> /etc/resolv.conf
+    fi
+  fi
+}
+
 # Retreive contextualization information
-CS="$(mktemp -d "cinit-XXXXXX")"
-rm -rf "$CS"
+CS="$(mktemp -d -t "cloud-config-XXXXXX")"
+NS="$(mktemp -d -t "network-config-XXXXXX")"
+rm -rf "$CS" "$NS"
 
 # Cleanup
 cleanup() {
-  rm -rf "$CS"
+  rm -rf "$CS" "$NS"
 }
 
 trap cleanup EXIT
@@ -69,6 +123,11 @@ blkid | grep 'TYPE="iso9660"' | awk -F ':' '{ print $1 }' | while read -r name; 
   elif [ -f "$CS".rom/openstack/latest/user-data ]; then
     cp "$CS".rom/openstack/latest/user-data "$CS"
   fi
+
+  if [ -f "$CS".rom/network-config ]; then
+    cp "$CS".rom/network-config "$NS"
+  fi
+
   umount "$CS".rom
 done
 rmdir "$CS".rom
@@ -89,6 +148,12 @@ if [ ! -f "$CS" ]; then
     printf "OK\n"
   else
     printf "ERR\n"
+  fi
+fi
+
+if [ -s "$NS" ]; then
+  if ! networkconfig "$NS"; then
+    log "error configuring network"
   fi
 fi
 
