Update setup tool to have some options including a reboot option (-r/--reboot)

diff --git a/rootfs/sbin/setup b/rootfs/sbin/setup
--- a/rootfs/sbin/setup
+++ b/rootfs/sbin/setup
@@ -2,55 +2,108 @@
 
 set -e
 
-if [ $# -ne 1 ]; then
-  printf >&2 "Usage: %s <disk>\n" "$(basename "${0}")"
-  exit 1
-fi
+: "${VERSION:=__VERSION__}"
 
-disk="${1}"
-part="${disk}1"
+rootfs=
+sources=
+disk=
+part=
 
-rootfs="/tmp/rootfs"
-sources="/mnt"
+SETUP_MBR=/usr/share/syslinux/mbr.bin
+SETUP_MEDIA=/dev/sr0
+SETUP_REBOOT=0
 
-mkdir -p "${sources}" "${rootfs}"
-
-cleanup() {
-  umount -f "${sources}"
-  umount -f "${rootfs}"
-  rm -rf "${rootfs}"
+warn() {
+  printf "WARN: %s\n" "$1" >&2
 }
 
-trap cleanup EXIT
+error() {
+  printf "ERROR: %s\n" "$1" >&2
+}
 
-dd bs=512 count=1 conv=notrunc,fsync if=/dev/zero of="${disk}"
+log() {
+  printf "%s\n" "$1" >&2
+}
 
-(
-  echo n # Add a new partition
-  echo p # Primary partition
-  echo 1 # Partition number
-  echo   # First sector (Accept default: 1)
-  echo   # Last sector (Accept default: varies)
-  echo a # Toggle bootable flag
-  echo 1 # Partition number
-  echo w # Write changes
-) | fdisk "${disk}"
+ok() {
+  printf "%s\n" "OK"
+}
 
-mkfs.ext2 "${part}"
+err() {
+  printf "%s\n" "ERR"
+}
 
-mount /dev/sr0 "${sources}"
+run() {
+  logfile="$(mktemp -t "setup-run-XXXXXX")"
+  if "$@" 2> "$logfile"; then
+    ok
+  else
+    err
+    tail -n -5 "$logfile" || true
+  fi
+  rm -rf "$logfile"
+}
 
-mount "${part}" "${rootfs}"
+progress() {
+  printf "%-30s" "$(printf "%s ... " "$1")"
+}
 
-(
-  cd "${rootfs}" || exit 1
-  zcat < "${sources}"/rootfs.gz | cpio -ivd
-)
+mount_sources() {
+  progress "Mounting sources"
+  sources="$(mktemp -d -t "setup-sources-XXXXXX")"
+  mount "$SETUP_MEDIA" "${sources}"
+}
 
-mkdir -p "${rootfs}"/boot/syslinux
-cp "${sources}"/kernel.gz "${rootfs}"/boot/vmlinuz
+create_rootfs() {
+  progress "Creating rootfs"
+  rootfs="$(mktemp -d -t setup-rootfs-XXXXXX)"
+}
 
-cat > "${rootfs}"/boot/syslinux/syslinux.cfg << EOF
+partition_disk() {
+  progress "Paritioning disk"
+
+  dd bs=512 count=1 conv=notrunc,fsync if=/dev/zero of="$disk"
+
+  (
+    echo n # Add a new partition
+    echo p # Primary partition
+    echo 1 # Partition number
+    echo   # First sector (Accept default: 1)
+    echo   # Last sector (Accept default: varies)
+    echo a # Toggle bootable flag
+    echo 1 # Partition number
+    echo w # Write changes
+  ) | fdisk "$disk" 1>&2
+}
+
+format_disk() {
+  progress "Formatting disk"
+  mkfs.ext2 "$part" 1>&2
+}
+
+mount_rootfs() {
+  progress "Mounting rootfs"
+  mount "$part" "$rootfs"
+}
+
+install_rootfs() {
+  progress "Installing rootfs"
+  (
+    cd "$rootfs" || exit 1
+    zcat < "$sources"/rootfs.gz | cpio -id
+  )
+}
+
+install_kernel() {
+  progress "Installing Kernel"
+  mkdir -p "$rootfs"/boot/syslinux
+  cp "$sources"/kernel.gz "$rootfs"/boot/vmlinuz
+}
+
+install_bootloader() {
+  progress "Installing Boot Loader"
+
+  cat > "$rootfs"/boot/syslinux/syslinux.cfg << EOF
 DEFAULT default
 
 LABEL default
@@ -58,8 +111,102 @@ LABEL default
 	APPEND quiet root=${part} rw
 EOF
 
-extlinux -s -i "${rootfs}"/boot/syslinux
+  extlinux -s -i "${rootfs}"/boot/syslinux 1>&2
+}
 
-dd bs=440 count=1 conv=notrunc,fsync if=/usr/share/syslinux/mbr.bin of="${disk}"
+install_mbr() {
+  progress "Installing MBR"
+  dd bs=440 count=1 conv=notrunc,fsync if="$SETUP_MBR" of="$disk"
+}
 
-echo "All Done!"
+unmount_rootfs() {
+  progress "Unmounting rootfs"
+  umount -f "$rootfs"
+  rm -rf "$rootfs"
+}
+
+unmount_sources() {
+  progress "Unmounting sources"
+  umount -f "$sources"
+  rm -rf "$sources"
+}
+
+cleanup() {
+  umount -f "$rootfs" 2> /dev/null
+  umount -f "$sources" 2> /dev/null
+  rm -rf "$sources"
+  rm -rf "$rootfs"
+}
+
+print_usage() {
+  cat << EOF
+Usage: $(basename "$0") [OPTS] [BLOCKDEVICE]
+
+Options:
+  -r/--reboot   -- Reboot after setup finishes
+  -h/--help     -- Display this help and exit
+  -V/--version  -- Display version and exit
+EOF
+}
+
+print_version() {
+  printf "%s v%s\n" "$(basename "$0")" "$VERSION"
+}
+
+_main() {
+  trap cleanup EXIT
+
+  while :; do
+    case $1 in
+      -r | --reboot)
+        SETUP_REBOOT=1
+        ;;
+      -V | --version)
+        print_version
+        exit 0
+        ;;
+      -h | --help)
+        print_usage
+        exit 0
+        ;;
+      --)
+        shift
+        break
+        ;;
+      -?*)
+        warn "invalid option $1"
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
+
+  if [ $# -eq 0 ]; then
+    disk="/dev/sda"
+  else
+    disk="$1"
+  fi
+
+  part="${disk}1"
+
+  steps="mount_sources create_rootfs partition_disk format_disk mount_rootfs"
+  steps="$steps install_rootfs install_kernel install_bootloader install_mbr"
+  steps="$steps unmount_rootfs unmount_sources"
+
+  for step in $steps; do
+    run "$step"
+  done
+
+  echo "All Done!"
+
+  if [ $SETUP_REBOOT = 1 ]; then
+    eject "$SETUP_MEDIA"
+    reboot
+  fi
+}
+
+if [ -n "$0" ] && [ x"$0" != x"-bash" ]; then
+  _main "$@"
+fi
